# Generated by Django 4.2.2 on 2023-07-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope_india', '0004_alter_student_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.FileField(null=True, upload_to='Avatar'),
        ),
    ]
