# Generated by Django 4.2.2 on 2023-07-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope_india', '0005_alter_student_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
