# Generated by Django 4.2.3 on 2023-07-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope_india', '0006_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hobby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
