# Generated by Django 4.2.3 on 2023-07-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope_india', '0009_remove_course_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(null=True),
        ),
    ]
