# Generated by Django 4.2.3 on 2023-07-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scope_india', '0010_course_course_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
