# Generated by Django 4.2.2 on 2023-07-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope_india', '0013_picked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
